version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=Stackbuld_DB;Username=postgres;Password=2809
      - Serilog__ElasticsearchUri=http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "5000:80"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=Stackbuld_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2809
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  pgdata:
    driver: local
